CREATE TABLE UserFeedback(
FeedbackID CHAR(36) PRIMARY KEY DEFAULT (UUID()),
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255),
Email VARCHAR(255) NOT NULL,
Message TEXT,
Subject VARCHAR(255) NOT NULL,
CreateDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
INDEX IX_UserFeedback_Email (Email)
);
